### ISSUE TITLE
Add Column.Scale to multiply a factor to scraped metrics

### ISSUE THREAD

**Issue by Vonng** [Vonng/pg_exporter#18]
It would be convenient to have the ability to scale metric value by a center factor.

E.g The origin metric is in µs , while common practice was transform those metrics into standard unit. such as second.

It would be annoying to do so in original raw SQL. But would be great to do it in configuration.

```yaml
    - exec_time:
        usage: COUNTER
        scale: 1e-6
        description: Total time spent executing the statement, in µs
```
